openapi: 3.0.2
info:
    title: API Documentation
    version: 1.0.0

paths:
    /users:
        get:
            summary: 'Lấy danh sách người dùng'
            responses:
                '200':
                    $ref: './components/responses.yaml#/UserListResponse'

    /users/{userId}:
        get:
            summary: 'Lấy thông tin một người dùng'
            parameters:
                - $ref: './components/parameters.yaml#/UserIdParam'
            responses:
                '200':
                    description: 'Thông tin người dùng'
                    content:
                        application/json:
                            schema:
                                $ref: './components/schemas.yaml#/User'
                '404':
                    $ref: './components/responses.yaml#/UserNotFoundResponse'
