export const EXCEPTIONS = {
    BAD_REQUEST: 400,
    UNAUTHORIZE: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
}

export const ERR_CODE = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    PASSWORD_ID_CORRECT: 'PASSWORD_ID_CORRECT',
    INVALID_INPUT: 'INVALID_INPUT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_FOUND_API: 'NOT_FOUND_API',
    FORBIDDEN: 'FORBIDDEN'
}
