UserIdParam:
    name: userId
    in: path
    required: true
    schema:
        type: string
    description: 'ID của người dùng'
    example: '550e8400-e29b-41d4-a716-446655440000'

PaginationParams:
    limit:
        name: limit
        in: query
        required: false
        schema:
            type: integer
            example: 10
        description: 'Số lượng item trên mỗi trang'

    page:
        name: page
        in: query
        required: false
        schema:
            type: integer
            example: 1
        description: 'Trang hiện tại của danh sách'
